# Generated by Django 3.2 on 2022-03-21 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20220316_1706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='organisation',
            new_name='organization',
        ),
    ]
