# Generated by Django 3.2 on 2022-03-23 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_auto_20220323_1118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_organizor',
            new_name='is_organizer',
        ),
    ]
